# Generated by Django 4.1.4 on 2022-12-29 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='title',
        ),
        migrations.AddField(
            model_name='food',
            name='carbohydrates',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='serving_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='serving_unit',
            field=models.CharField(default='serving', max_length=50),
        ),
        migrations.AddField(
            model_name='food',
            name='total_fat',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.ManyToManyField(related_name='meal', to='diet.meal'),
        ),
    ]
