# Generated by Django 4.1.4 on 2022-12-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('PR', models.IntegerField(default=0)),
                ('reps', models.IntegerField(default=0)),
                ('sets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('exercises', models.ManyToManyField(to='api.exercise')),
            ],
        ),
    ]
