# Generated by Django 4.1.4 on 2022-12-31 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_pr_exercise_weight_remove_exercise_sets_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='gifURl',
            new_name='gifUrl',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='bodyPart',
        ),
    ]
