# Generated by Django 4.1.4 on 2023-01-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exercise_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='reps',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='weight',
        ),
    ]
